### ISSUE TITLE
PSM Games

### ISSUE THREAD

**Issue by JohnnyLove007** [Rinnegatamante/AntiBlacklist#4]
is it possible to add PSM games to play on PS VITA TV?

**Comment by Rinnegatamante** [comment]
Talked with @frangarcj about this.
Seems it's a specific value set in app.info file in each PSM game.
The best way to fix this is via a plugin so that patch will eventually come in a new suprx plugin or inside NoPsmDrm itself.

Btw it's not something related to AntiBlacklist so closing this issue.

**Comment by JohnnyLove007** [comment]
Thanks
